<?php

/**
 * @file
 * Contains academy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function academy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the academy module.
    case 'help.page.academy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function academy_theme() {
  return [
    'academy' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function academy_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {

  switch ($form_id) {
    case 'node_article_form':
      //se utente non ha permesso handle article any country =>
      if (! \Drupal::currentUser()->hasPermission(
          'handle article any country'
        )) {
        $user = \Drupal\user\Entity\User::load(Drupal::currentUser()->id());
        $value = $user->field_country->value();
        $form['field_country']['#access'] = FALSE;
        $form['field_country']['#default_value'] = $value;
      }

      break;
  }
}